name: Terraform Deployment on the Github Actions.

on:
  push:
    branches:
      - main
    tags:
      - 'deploy-*'
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage (dev or prod)'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_stage: ${{ github.event.inputs.stage || (startsWith(github.ref, 'refs/tags/deploy-dev') && 'dev') || (startsWith(github.ref, 'refs/tags/deploy-prod') && 'prod') || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -var-file=${{ env.TF_VAR_stage }}_config.tfvars
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=${{ env.TF_VAR_stage }}_config.tfvars
        working-directory: ./terraform

