name: Terraform Lifecycle

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Environment (Dev or Prod)"
        required: true
        default: Dev
      action:
        description: "Terraform action (apply or destroy)"
        required: true
        default: apply

  push:
    branches:
      - main
    tags:
      - "deploy-dev"
      - "deploy-prod"

jobs:
  terraform:
    name: Terraform Lifecycle
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Stage and Action from Inputs or Tag
        id: set_vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "STAGE=${{ github.event.inputs.stage }}" >> $GITHUB_ENV
            echo "ACTION=${{ github.event.inputs.action }}" >> $GITHUB_ENV
          else
            ref_name="${GITHUB_REF##*/}"
            if [[ "$ref_name" == deploy-dev* ]]; then
              echo "STAGE=Dev" >> $GITHUB_ENV
            elif [[ "$ref_name" == deploy-prod* ]]; then
              echo "STAGE=Prod" >> $GITHUB_ENV
            else
              echo "STAGE=Dev" >> $GITHUB_ENV
            fi
            echo "ACTION=apply" >> $GITHUB_ENV
          fi

      - name: Normalize STAGE to lowercase for filenames
        run: echo "STAGE_LOWER=$(echo $STAGE | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -backend-config="key=${STAGE}.tfstate"
        working-directory: terraform

      - name: Terraform Workspace Select or Create
        run: |
          terraform workspace list
          if terraform workspace list | grep -qw "${STAGE}"; then
            terraform workspace select "${STAGE}"
          else
            terraform workspace new "${STAGE}"
          fi
        working-directory: terraform

      - name: Terraform Validate and Plan
        run: |
          terraform validate
          if [ "${ACTION}" = "destroy" ]; then
            terraform plan -destroy -var-file="${STAGE_LOWER}_config.tfvars" -out=tfplan
          else
            terraform plan -var-file="${STAGE_LOWER}_config.tfvars" -out=tfplan
          fi
        working-directory: terraform

      - name: Terraform Apply
        if: env.ACTION == 'apply'
        run: terraform apply -auto-approve tfplan
        working-directory: terraform

      - name: Terraform Destroy
        if: env.ACTION == 'destroy'
        run: terraform destroy -auto-approve -var-file="${STAGE_LOWER}_config.tfvars"
        working-directory: terraform

      - name: Debug Terraform Outputs
        if: env.ACTION == 'apply'
        run: terraform output
        working-directory: terraform

      - name: Get EC2 Public IP
        id: ec2_ip
        if: env.ACTION == 'apply'
        working-directory: terraform
        run: |
          set -e
          EC2_IP=$(terraform output writeonly_instance_public_ip | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n1 | tr -d ' \t\n\r')
          if [[ -z "$EC2_IP" ]]; then
            echo "Terraform output was invalid or empty"
            exit 1
          fi
          echo "ec2_ip<<EOF" >> "$GITHUB_OUTPUT"
          echo "$EC2_IP" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Wait for port 80 to be available
        if: env.ACTION == 'apply'
        env:
          EC2_IP: ${{ steps.ec2_ip.outputs.ec2_ip }}
        working-directory: terraform
        shell: bash
        run: |
          echo "🌐 Waiting for app at http://$EC2_IP"
          echo "📡 EC2_IP resolved to: $EC2_IP"

          echo "🔎 Waiting for port 80 to open using netcat (nc)..."
          MAX_PORT_ATTEMPTS=30
          for i in $(seq 1 $MAX_PORT_ATTEMPTS); do
            if nc -z "$EC2_IP" 80; then
              echo "✅ Port 80 is open"
              break
            fi
            echo "❌ Port 80 not open yet. Attempt $i of $MAX_PORT_ATTEMPTS. Retrying in 5 seconds..."
            sleep 10
          done

          echo "🌐 Verifying HTTP response with curl..."
          MAX_ATTEMPTS=30
          for i in $(seq 1 $MAX_ATTEMPTS); do
            echo "⏳ Attempt $i..."
            STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://$EC2_IP")
            echo "➡️ Status Code: $STATUS_CODE"

            if [[ "$STATUS_CODE" == "200" ]]; then
              echo "✅ App is reachable at http://$EC2_IP"
              exit 0
            fi

            echo "❌ Not reachable yet. Retrying in 10 seconds..."
            sleep 10
          done

          echo "❌ Failed: App not reachable after $MAX_ATTEMPTS attempts"
          exit 1
